language: c
sudo: required
addons:
  apt:
    packages:
    - build-essential
    - git
script:
  - cd installer/target
  - make rbp1 > /tmp/log.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - /tmp/log.sh
  on:
    all_branches: true
