version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: cd installer/target && make rbp1
      - run: mkdir -p /tmp/artifacts
      - run: cp installer/target/buildroot-*/output/images/OSMC_TGT_rbp1_*.img.gz /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /circle-.*/
